export const GET_INFO_FILMS = 'GET_INFO_FILMS';
export const GET_INFO_FILM = 'GET_INFO_FILM';
export const GET_PREVIOUSLY_VIEWED = 'GET_PREVIOUSLY_VIEWED';

export const  UPDATE_FAVORITES = 'UPDATE_FAVORITES';
export const  GET_FAVORITES = 'GET_FAVORITES';
